### ISSUE TITLE
Issue with Song Title or Artist Name with Japanese & Korean characters

### ISSUE THREAD

**Issue by andykamezou** [Exle/AIMP-Discord-Presence#1]
The **_Song Title_** or **_Artist Name_** are not completely shown if there's no Latin characters.

Example when both Japanese **_Song Title_** and **_Artist Name_** don't have any Latin characters :
![both name and title not fully shown jp](https://user-images.githubusercontent.com/6763353/38856415-029564ce-4259-11e8-82a4-76e84734e936.png)

Example of complete **_Song Title_** that use Latin character, but incomplete Japanese **_Artist Name_** :
![name not fully shown jp](https://user-images.githubusercontent.com/6763353/38856458-1a1e0dee-4259-11e8-9074-4f9597cf6f2b.png)

Example of complete Korean **_Artist Name_** that includes Latin character, but incomplete **_Song Title_** :
![title not fully shown kr](https://user-images.githubusercontent.com/6763353/38856468-240dc588-4259-11e8-815d-3a834f3e96fd.png)

Example when both Korean **_Song Title_** and **_Artist Name_** includes Latin characters :
![all shown correctly kr](https://user-images.githubusercontent.com/6763353/38856474-2773d33e-4259-11e8-8747-7bd9196b11a2.png)

**Comment by Exle** [comment]
Will be fixed in the next version
