### ISSUE TITLE
Падает плеер

### ISSUE THREAD

**Issue by 3soolo3** [Exle/AIMP-Discord-Presence#11]
Падает при попытке проиграть радиостанцию http://ic6.101.ru:8000/p451591
Теги радиостанции слегка специфические:
![default](https://user-images.githubusercontent.com/16206472/51455515-f2d7c580-1d5a-11e9-92a2-cbafdf8a1be0.png)

**Comment by ArtemIzmaylov** [comment]
More details is here https://github.com/Exle/AIMP-Discord-Presence/issues/12

**Comment by Exle** [comment]
Fixed with commit b2e42290cd60ea6a559719b5e4a0b9e4e0e09cd4
