### ISSUE TITLE
[BUG] Possible memory corruption

### ISSUE THREAD

**Issue by ArtemIzmaylov** [Exle/AIMP-Discord-Presence#12]
Plugin uses static size array to copy the data from the player:

```
BOOL AIMPRemote::InfoUpdateTrackInfo()
{
	WCHAR buffer[256];
```
But it does not check actual value length before copy the data:
```
        memcpy(buffer, offset, AIMPRemote_TrackInfo->AlbumLength * 2);
	buffer[AIMPRemote_TrackInfo->AlbumLength] = 0;
```
So, if length of value in tag field is more or equal to 256 symbols plugin produces a memory corruption.

**Comment by Exle** [comment]
Fixed with commit b2e42290cd60ea6a559719b5e4a0b9e4e0e09cd4
