### ISSUE TITLE
[ISSUE] The plugin refuses to work

### ISSUE THREAD

**Issue by bscout9956** [Exle/AIMP-Discord-Presence#15]
I have tried reinstalling but no matter what I do, rich presence won't work.

AIMP Version:
![image](https://user-images.githubusercontent.com/24628639/74093536-d87da080-4ab1-11ea-888a-bc44e1ec8195.png)
Discord Version:
![image](https://user-images.githubusercontent.com/24628639/74093541-e7fce980-4ab1-11ea-90e5-e72ffcd38e9d.png)

**Comment by airi-san** [comment]
it's seems not just me experiencing this issue... i have same problem,The plugin not working anymore.

-Discord
Stable 54234 (7932b09)
Host 0.0.305
Windows 10 64-Bit (10.0.17763)

-AIMP
v.460, build 2170
(13.01.2020)

**Comment by airi-san** [comment]
nvm.... 
[https://pasteboard.co/IUa8TJY.png]

**Comment by airi-san** [comment]
nvm...
[https://pasteboard.co/IUa8TJY.png](Image)

**Comment by airi-san** [comment]
nvm...
[Image](https://pasteboard.co/IUa8TJY.png)

**Comment by bscout9956** [comment]
![image](https://user-images.githubusercontent.com/24628639/74600038-19555680-506a-11ea-88a6-905da70f26c0.png)
NVM2
