### ISSUE TITLE
Discord GameSDK migration

### ISSUE THREAD

**Issue by vzabrodin** [Exle/aimp-discord-presence#16]
Discord RPC is now deprecated. [Discord GameSDK ](https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide) is replacing it.
You can **finally** set an activity type there. Don't know about album art

**Comment by Daendaralus** [comment]
As said said in another [issue](https://github.com/Exle/AIMP-Discord-Presence/issues/17#issuecomment-606107314), while you can set the activity type in the GameSDK this is entirely ignored by Discord. So for now we're stuck on [Playing] even when upgraded to the GameSDK. 

On another note, I've done the migration and an ugly fix to [this issue](https://github.com/Exle/AIMP-Discord-Presence/issues/20#issue-603221414) on my fork. Not sure if I should open a pull request - the commit isn't very clean.
