### ISSUE TITLE
Проблема с русской кодировкой

### ISSUE THREAD

**Issue by LodiurZ** [Exle/AIMP-Discord-Presence#18]
![image](https://user-images.githubusercontent.com/58341351/77234817-51e4d480-6bc2-11ea-8a06-8ff35a0f23c4.png)
"Тайна"

**Comment by Exle** [comment]
Fixed with commit 42ba79e4b1db97043de59d1b5f88dd0562744c34

**Comment by Exle** [comment]
Fixed with commit 42ba79e4b1db97043de59d1b5f88dd0562744c34
