### ISSUE TITLE
Track names not showing if there's a non-latin one-character name in any of the Title, Artist or Album

### ISSUE THREAD

**Issue by Rivan2** [Exle/aimp-discord-presence#19]
![2020-04-18_035426_cr1](https://user-images.githubusercontent.com/22899860/79624876-87cb9900-812d-11ea-9a43-2d06f67837d4.png)

**Comment by DanilChil** [comment]
Была похожая проблема. Точнее, в Discord совсем не отображалась информация о песне. Нашел сам плагин в AIMP, выключил. После этого перезапустил программу и опять включил плагин. Надеюсь, поможет.

**Comment by tooruu** [comment]
Прошу решить эту проблему. Очень надоедает т.к. слушаю много песен от одного исполнителя у кого названия альбомов состоят из одного символа.
