### ISSUE TITLE
If paused - stop rich pressence

### ISSUE THREAD

**Issue by BahamutxD** [Exle/aimp-discord-presence#20]
Allow the option to remove what I'm listening if the player is paused/stopped to avoid displaying what I'm listening indefinitely while player is inactive but still running.

Or let other apps (games) display over AIMP if they are focused.

**Comment by Chortowod** [comment]
still no chance to do it?

**Comment by RDMCz** [comment]
I would also love to have this feature. For now, the only solution is sticking with 1.0.0.7

**Comment by AndroginKlim** [comment]
> I would also love to have this feature. For now, the only solution is sticking with 1.0.0.7

how i can download 1.0.0.7 ver

**Comment by RDMCz** [comment]
[Exle AIMP Discord Presence 1.0.0.7.zip](https://github.com/Exle/AIMP-Discord-Presence/files/14002457/Exle.AIMP.Discord.Presence.1.0.0.7.zip)

**Comment by AndroginKlim** [comment]
it dont work


> [Exle AIMP Discord Presence 1.0.0.7.zip](https://github.com/Exle/AIMP-Discord-Presence/files/14002457/Exle.AIMP.Discord.Presence.1.0.0.7.zip)
