### ISSUE TITLE
[Feature Request] Dynamic Cover Art

### ISSUE THREAD

**Issue by Hexality** [Exle/aimp-discord-presence#28]
Hi, I came to ask if is there anything related to dynamic cover arts on rich presence planned for future releases.

Discord added a while ago an option to load images from external sources, making it kinda easy to display the album art on profile (by using mp:external source)

I was thinking a bit about it and you could even do a thing where it would get both Artist+Album outputs and place on MusicBrainz api and then retrieve the cover art from coverartarchive

(Example using powershell since I don't know C#/C++ or related)

AIMP
> ↳ Metadata output:
>> ↳ Artist/Album

Example (Splitted): 
```powershell
$artist="Illenium"
$album="ASCEND"

$getData = ((Invoke-WebRequest -Uri 'http://musicbrainz.org/ws/2/release-group/?query=artist:$($artist)%20ANDalbum:$($ascend)&fmt=json' -ContentType 'application/json').Content | ConvertFrom-Json).'release-groups'[0] 
# Request data from the api, converts response from json into an object, navigates to the "release-groups" section of the json then selects just the first object of the array

$albumArt = iwr -uri "http://coverartarchive.org/release-group/$($getData.id)/front" -OutFile ./album.jpg 
# Gets the album from the archive using the id retrieved previously
```

$albumArt 
`# result = http://coverartarchive.org/release-group/db17ce16-aacf-4157-a551-b9e53b270cbc/front`
![Cover](http://coverartarchive.org/release-group/db17ce16-aacf-4157-a551-b9e53b270cbc/front-500)

**Comment by Hexality** [comment]
to use with discord's api I think it was something like mp:external/url

**Comment by Chris3461** [comment]
Hello, did anyone find out how to do it?
