### ISSUE TITLE
Статус "Играет в игру" вместо "Слушает"

### ISSUE THREAD

**Issue by yarik2720** [Exle/AIMP-Discord-Presence#3]
Обратил внимание на то, что приложение Spotify отдает статус "Слушает", возможно ли так же сделать и в плагине для AIMP?
![discord_2018-04-27_16-45-51](https://user-images.githubusercontent.com/1839978/39365700-8edf85b6-4a3a-11e8-8881-b93a63a7f6cc.png)
![discord_2018-04-27_16-46-44](https://user-images.githubusercontent.com/1839978/39365715-9afdaab2-4a3a-11e8-9c99-73aeab878082.png)

**Comment by Exle** [comment]
@yarik2720 возможно, писал уже [тут](http://www.aimp.ru/forum/index.php?topic=59461.msg369223#msg369223)
