### ISSUE TITLE
AIMP resets back to default any modified plugin parameter in AIMP.ini

### ISSUE THREAD

**Issue by ElTioRata** [Exle/aimp-discord-presence#32]
Current workaround is setting the file as read-only.

**Comment by Exle** [comment]
AIMP must be closed to edit AIMP.ini.

**Comment by ElTioRata** [comment]
But I closed it before making any changes.

**Comment by Exle** [comment]
I can't help with this. AIMP loads the config at the start of the application and overwrites all data upon closing. The plugin does not change the settings, they remain as they were when the application was started.

**Comment by ElTioRata** [comment]
nvm, looks like the issue fixed itself
