### ISSUE TITLE
Album Art

### ISSUE THREAD

**Issue by bbenance** [Exle/AIMP-Discord-Presence#4]
Would it be possible to add the album art of the song you are playing as the main image for the presence, similar to how the Spotify integration handles it?

**Comment by iCrawl** [comment]
No, not possible. Discord puts heavy restrictions on this.

**Comment by ArztVielfrass** [comment]
http://www.aimp.ru/forum/index.php?topic=59461.msg369100#msg369100
Not sure if you can use `discord.largeImageKey` and `discord.smallImageKey` to update the album art. I wasn't aware of the restrictions, been looking if such exists.

**Comment by iCrawl** [comment]
There currently is no support for this in the public API.

Those images need to be pre-uploaded. There is talk about allowing dynamic images to be added though.
https://github.com/discordapp/discord-rpc/issues/70

**Comment by Isa27-0** [comment]
Besides not being supported, it can break the ToS. As mentioned in https://github.com/PreMiD/Presences/issues/1837

**Comment by Hexality** [comment]
It is possible right now to use external iamges on rich presence by using mp:external/url tag,
