### ISSUE TITLE
[Sugsetion] image of song/album on rich presence

### ISSUE THREAD

**Issue by Methosss** [Exle/aimp-discord-presence#8]
I suggest adding an song/album image to the rich presence.
![image](https://user-images.githubusercontent.com/32804020/43479536-ea597382-9500-11e8-9a2a-c876ee7b9ef3.png)

**Comment by flameshikari** [comment]
@MentosPL https://github.com/Exle/AIMP-Discord-Presence/issues/4#issuecomment-405191111
