### ISSUE TITLE
.flac

### ISSUE THREAD

**Issue by lmao-emerald** [Exle/AIMP-Discord-Presence#9]
Won't work with .flac files

**Comment by Moetsuki** [comment]
Works fine with me and my library is entirely FLAC

![image](https://user-images.githubusercontent.com/44203953/47169334-de270400-d30b-11e8-98e9-812a6179d767.png)

![image](https://user-images.githubusercontent.com/44203953/47169357-eed77a00-d30b-11e8-8a53-d39c57a4c560.png)
